# Generated by Django 5.2.7 on 2025-10-21 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0002_remove_customer_phone_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
