# Generated by Django 5.2.7 on 2025-10-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0003_remove_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='newsletter',
            field=models.BooleanField(default=True),
        ),
    ]
