# Generated by Django 5.2.7 on 2025-10-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0006_bill_product_order_producttype_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
