# Generated by Django 5.2.7 on 2025-10-24 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0007_alter_customer_options_customer_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
    ]
