# Generated by Django 5.2.7 on 2025-10-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0008_alter_customer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
